### ISSUE TITLE
Can you briefly describe the data processing process?

### ISSUE THREAD

**Issue by twodoge** [ZhengPeng7/Multi_column_CNN_in_Keras_for_crowd_counting#1]
I don't quite understand how the data is processed.

**Comment by ZhengPeng7** [comment]
> I don't quite understand how the data is processed.

Hi, what do you mean the 'process'?
Generating the density map or some data preprocessing on the image data?

**Comment by twodoge** [comment]
> > I don't quite understand how the data is processed.
> 
> Hi, what do you mean the 'process'?
> Generating the density map or some data preprocessing on the image data?

Generating the density map

**Comment by ZhengPeng7** [comment]
> > > I don't quite understand how the data is processed.
> > 
> > 
> > Hi, what do you mean the 'process'?
> > Generating the density map or some data preprocessing on the image data?
> 
> Generating the density map

Very easy to you. At first, make a pure black canvas, of which the size is same as the RGB image , and Ground Truth is given as (x_1, y_1), (x_2, y_2) ..., for every axis pair, put a gaussian kernel onto the canvas. Since the 99.7% of a Gaussian Distribution is in the area that sigma <=3,

so if *Fixed Value(sigma)* = 15, you can cut the rectangle area as the whole kernel:
gaussian_map = np.multiply(
                cv2.getGaussianKernel(gaussian_radius\*2+1, sigma),
                cv2.getGaussianKernel(gaussian_radius\*2+1, sigma).T
            ),
then:
gaussian_map /= np.sum(gaussuian_map)   # use normalization to fix the missing of things outside 3sigma(1-99.7% part),
canvas += gaussian_map`
Go over all the GT points, a density map is generated by fixed value method.

Adaptive method: all the difference is the sigma(gaussian_radius/3). The sigma is not fixed value, and now denpends on the nearest three GT points to it. So you can set the sigma as, for example,  sum(the_distances_to_the_three_nearest_points) / 10.

May my poor explanation help you.
